name: Linters

on:
  pull_request: null
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:

  spelling:
    name: Spell check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip-codespell"

      - name: Install codespell
        run: |
          pip install --user 'codespell>=2.2'

      - name: Search for misspellings
        run: |
          "$(python -m site --user-base)/bin/codespell"
